INSTALL_TARGET_PROCESSES = SpringBoard

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = AutoConfirm

AutoConfirm_FILES = Tweak.x
AutoConfirm_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
